### ISSUE TITLE
[BUG] Can not open the plugin

### ISSUE THREAD

**Issue by minchowang** [bitlap/intellij-sbt-dependency-analyzer#103]
### Preparation action completed
- [x] have added `addDependencyTreePlugin` into `plugins.sbt` (sbt.1.4+)
- [x] have set `organization := ` for root project and cross-platform

### Screenshot of the current sbt Shell

<img width="548" alt="image" src="https://github.com/bitlap/intellij-sbt-dependency-analyzer/assets/33626973/b74b6703-8f00-4f62-819b-54751ae9a923">

### Screenshot of the current dependency tree 

your images

### Scala platform（scala js, scala jvm, scala native）and version (scala 2.x, scala 3.x)

scala 2.x

your images or text

### IDEA version comes from `About Intellij IDEA`

> sbt --version
sbt version in this project: 1.10.1
sbt script version: 1.10.0

Idea version: 2024.1.2

**Comment by jxnu-liguobin** [comment]
@minchowang Thank you for your feedback. 
Is it always showing as loading or there is nothing?

**Comment by jxnu-liguobin** [comment]
2024.1 version will be supported in 0.4.0
