### ISSUE TITLE
[BUG] No dependencies display

### ISSUE THREAD

**Issue by elgca** [bitlap/intellij-sbt-dependency-analyzer#118]
### Preparation action completed
- [x] I have added `addDependencyTreePlugin` into `plugins.sbt` (sbt.1.4+) or the file `sdap.sbt` exists and contains `addDependencyTreePlugin`
- [x] I have set `organization := ` for root project and cross-platform

### Screenshot of the current sbt Shell
![image](https://github.com/user-attachments/assets/288b970a-b177-4e28-976e-7bfd2f59c20c)

### Screenshot of the current dependency tree 

![image](https://github.com/user-attachments/assets/37d8b24a-a33a-4984-8fe7-d1573835cf9f)

![image](https://github.com/user-attachments/assets/8065c272-2c8c-4edd-b7cf-c00e6631a46f)

![image](https://github.com/user-attachments/assets/2ce1fccf-01ce-4153-8695-18477509c058)

![image](https://github.com/user-attachments/assets/f2b81de2-b7ef-453e-9457-684080dc2623)

![image](https://github.com/user-attachments/assets/70ac465f-c6a7-490c-9084-4066e084dd87)

### Scala platform (scala js, scala jvm, scala native) and version (scala 2.x, scala 3.x)

- windows 11
- scala3.6.0
- scalajs1.17
- sbt 1.10.2
- 

### IDEA version comes from `About Intellij IDEA`

- 2024.3 EAP

![image](https://github.com/user-attachments/assets/063cd339-0996-4ba8-bc26-61b706b4742c)

### dot files

[dependencies-compile.zip](https://github.com/user-attachments/files/17449842/dependencies-compile.zip)

**Comment by jxnu-liguobin** [comment]
Modules not listed in `moduleName` will not be analyzed. So only scala-web-full displays normally.
This is because module dependency analysis relies on mouduleName as the artifact ID

**Comment by elgca** [comment]
So, how do you configure build.sbt? A project with Scala, GFLOT (JVM + JS), and a JS.
looks like:
```scala

lazy val root =
  project
    .in(file("."))
    .aggregate(shared.js, shared.jvm, backend, frontend) //
    .settings(commonSettings)
    .settings(
      scalaVersion := Versions.Scala,
      name := Versions.ProjectName,
    )
    .settings(rootSettings)
    .rootPlugins

lazy val shared = crossProject(JSPlatform, JVMPlatform)
  .in(modules("shared"))
  .enablePlugins(BuildInfoPlugin)
  .settings(commonSettings)
  .settings(sharedDeps)
  .jvmSettings(sharedJvmDeps)
  .sharedPlugins

lazy val backend = project
  .dependsOn(shared.jvm)
  .settings(commonSettings)
  .in(modules("backend"))
  .settings(backendSettings)
  .backendPlugins

lazy val frontend = project
  .in(modules("frontend"))
  .dependsOn(shared.js)
  .enablePlugins(ScalaJSPlugin)
  .settings(commonSettings)
  .settings(frontendSettings)
  .frontendPlugins

```
________________________________
发件人: 梦境迷离 ***@***.***>
发送时间: 2024年10月20日 18:56
收件人: bitlap/intellij-sbt-dependency-analyzer ***@***.***>
抄送: kewenchao ***@***.***>; Author ***@***.***>
主题: Re: [bitlap/intellij-sbt-dependency-analyzer] [BUG] No dependencies display (Issue #118)


Modules not listed in moduleName will not be analyzed. So only scala-web-full displays normally.
This is because module dependency analysis relies on mouduleName as the artifact ID

―

**Comment by jxnu-liguobin** [comment]
@elgca  Unfortunately, the root project in your config has already used `aggregate`, but sbt 'moduleName' doesn't list the dependent module names, I didn't encounter this exception in test project `circe`, since I'm not good at cross-platform, I can't see the difference between your config and `circe`, So, I'll rule it out when I have time this week, can you provide a minimal project to reproduce it?

**Comment by elgca** [comment]
It might have been caused by IDEA. Today, after IDEA crashed and failed to load the project, I have to clear anything about IDEA 
cache or  config. then reopen the project. Now it's working
