### ISSUE TITLE
The plugin can't find dependencies (Idea version: #IC-232.8660.185)

### ISSUE THREAD

**Issue by grouzen** [bitlap/intellij-sbt-dependency-analyzer#2]
I see a 'nothing found' message for different projects.

**Comment by jxnu-liguobin** [comment]
> I see a 'nothing found' message for different projects.

Would you add AddDependencyPlugin in sbt plugin.sbt, please?

**Comment by grouzen** [comment]
Ah yeah, sorry, forgot to mention that it doesn't work when the `addDependencyPlugin` is added.

**Comment by jxnu-liguobin** [comment]
> Ah yeah, sorry, forgot to mention that it doesn't work when the `addDependencyPlugin` is added.

Can you take a screenshot of the sbt shell?

**Comment by grouzen** [comment]
Hey! It was dependencyDot issue. Fixed by installing the latest version! Thanks for the help!
