### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by gptshubham595** [bitlap/intellij-sbt-dependency-analyzer#94]
I have installed the plugin 
then beside dependency analyzer I got an option of sbt dependency analyze on tapping, it shows No project.

How to use this this plugin?

Android Studio Iguana
Mac

**Comment by jxnu-liguobin** [comment]
@gptshubham595 Thank you for your feedback. Could you provide a screenshot of the studio version number and No Project?

**Comment by gptshubham595** [comment]
Android Studio Iguana | 2023.2.1 Patch 
<img width="1334" alt="Screenshot 2024-05-01 at 1 15 54 PM" src="https://github.com/bitlap/intellij-sbt-dependency-analyzer/assets/24877361/df46a696-0543-4389-b0cb-95a1711acf48">

**Comment by jxnu-liguobin** [comment]
Sorry. It only supports SBT. Gradle is supported in the intellij IDEA, so it is not within the scope of this plugin.
